config/routes.rb
MwhJi::Application.routes.draw do
  get 'answer/:id' => "questions#answer", :as => "answer_question"
  post 'answer/:id' => "questions#post_answer", :as => "post_answer"
  get "login" => "game#login", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  root :to => 'game#index'
  resources :sessions, :users, :questions, :answers
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :question_id, :user_id, :point_value

  belongs_to :user
  belongs_to :post
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :query, :picture, :user_id, :point_value

  has_attached_file :picture

  belongs_to :user
  has_many :answers

  def preview
  	if self.query.length > 15
  		self.query[0..11]+"..."
  	else
  		self.query
  	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :login, :password, :password_confirmation, :admin, :name

  has_many :questions
  has_many :answers

  def points
  	t = 0
  	self.answers.all.each do |a|
  		t += a.point_value
  	end
  	t
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		@answer = Answer.new(params[:answer])
		@question = Question.find(@answer.question_id)

		if @answer.content == @question.answer
			@answer.point_value = @question.point_value
		else
			@answer.point_value = 0 - @question.point_value
		end

		@content = @answer.content

		if @answer.save
			respond_to do |format|
				format.js
			end
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	before_filter :check_session

  	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def check_session
		if !current_user
			redirect_to login_path
		end
	end

	helper_method :current_user
end

app/controllers/game_controller.rb
class GameController < ApplicationController
	skip_before_filter :check_session, :only=> [:login]

	def index
		@users_by_points = User.all.sort! { |a,b| a.points <=> b.points }.reverse()
	end

	def login
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def new
		@question = Question.new
	end

	def create
		@question = Question.new(params[:question])
		if @question.save
			redirect_to root_url
		else
			render "new"
		end
	end

	def answer
		@question = Question.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :check_session, :only=> [:create]

	def create
		user = User.find_by_email(params[:login]) || User.find_by_login(params[:login])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path, :notice => "Logged in!"
		else
			flash.now.alert = "Invalid email or password"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to root_url, :notice => "Signed up!"
		else
			render "new"
		end
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_response.html.erb
<h2>
	<% if @answer.point_value > 0 %>
		Great job! You answered '<%= @answer.content %>' and got <%= @answer.point_value %> points!
	<% else %>
		Sorry, dude! You answered '<%= @answer.content %>' and lost <%= 0 - @answer.point_value %> points!
	<% end %>
</h2>

<br>

<a href='/'>Take me home</a>

app/views/answers/create.js.erb
$(".overlay").show().fadeTo(300, 0.8);
$(".overlay .container .content").html("<%=escape_javascript render 'response', {:answer => @answer} %>");

app/views/game/index.html.erb
<div class="four columns alpha">
	<h2> Quick Links </h2>
	<ul>
		<li><%= link_to "New Question", new_question_path %></li>
		<li><%= link_to "Quiz Me!", "#!" %></li>
		<li>You have <%= current_user.points %> points. </li>
	</ul>
</div>
<div class="four columns">
	<h2> All Questions </h2>
	<ul>
	<% Question.all.each do |q| %>
		<li><%= link_to q.preview, answer_question_path(q) %></li>
	<% end %>
	</ul>
</div>
<div class="four columns omega">
	<h2> My Questions </h2>
	<ul>
	<% current_user.questions.each do |q| %>
		<li><%= link_to q.preview, answer_question_path(q) %></li>
	<% end %>
	</ul>
</div>
<div class="four columns">
	<h2> Leaderboard </h2>
	<ul>
	<% @users_by_points.each do |u| %>
		<li><%= u.name %> - <%= u.points %> points</li>
	<% end %>
</ul>
</div>

app/views/game/login.html.erb
<div class="centered login">
	<h1>Log in</h1>

	<%= form_tag sessions_path do %>
		<div class="field">
			<%= text_field_tag :login, params[:login], :placeholder => "Username or Email" %>
		</div>
		<div class="field">
			<%= password_field_tag :password, nil, :placeholder => "Password" %>
		</div>
		<div class="actions">
			<%= submit_tag "Log in" %>
		</div>
	<% end %>
	<%= current_user %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MwhJi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='topbar'>
	<div class="container">
		<div class="logo">
			<%= link_to "MWH-JI Trivia", root_url %>
		</div>
		<% if current_user %>
			<div class="user">
				Logged in as <%= current_user.name %> - <%= link_to "Log Out?", logout_path %>
			</div>
		<% end %>
	</div>
</div>
<div class="overlay">
	<div class="container">
		<div class="content">
			Bob
		</div>
	</div>
</div>
<div class="container">
	<div>
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/questions/answer.html.erb
<div class="question centered">
	<% if @question.picture %>
		<%= image_tag @question.picture.url, :class => "question_picture" %>
	<% end %>
	<h2><%= @question.query %></h2>
	<%= form_for Answer.new, :remote => true do |f| %>
		<%= f.hidden_field :user_id, :value => current_user.id %>
		<%= f.hidden_field :question_id, :value => @question.id %>
		<%= f.text_field :content, :placeholder => "Answer" %><br>
		<%= f.submit :value => "Attempt" %>
	<% end %>
</div>

app/views/questions/new.html.erb
<div class="login centered">
  <h1>New Question</h1>
  <%= form_for @question do |f| %>
    <div class="field">
      <%= f.text_field :query, :placeholder => "Query" %>
    </div>
    <div class="field">
      <%= f.text_field :answer, :placeholder => "Answer" %>
    </div>
    <div class="field">
      <%= f.file_field :picture %> Optional picture
    </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="login centered">
  <h1>New User</h1>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.text_field :email, :placeholder => "Email Address" %>
    </div>
    <div class="field">
      <%= f.text_field :login, :placeholder => "Username" %>
    </div>
    <div class="field">
      <%= f.text_field :name, :placeholder => "Name" %>
    </div>
    <div class="field">
      <%= f.password_field :password, :placeholder => "Password" %>
    </div>
    <div class="field">
      <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
    </div>
    <%= f.check_box :admin %> Admin?
    <div class="actions"><%= f.submit %></div>
  <% end %>
</div>